### ISSUE TITLE
May I ask what is the use of this loader?

### ISSUE THREAD

**Issue by mrshawn191** [tomasAlabes/ko-loader#1]
May I ask what is the use of this loader?

**Comment by tomasAlabes** [comment]
knockout exposes `ko` in the window object, with this loader I replace the code that does that and avoid that.

**Comment by mrshawn191** [comment]
Aha thanks may I also ask why that would be an issue to replace ko in global variable?

**Comment by tomasAlabes** [comment]
Always is a good practice to leave the window object clean. And ko needs $ as global too, so it drags it too. 

I've also found ko leaks too, so if you have it global and you have multiple components using ko you might face memory problems because of lack of isolation. It's mostly a matter of encapsulation.

**Comment by mrshawn191** [comment]
Aha I see... May I also ask, you use this loader only for knockout.debug correct? So it will only work locally but not in production use? 

Also may I ask, i recently upgraded to webpack 3+ but one of my jquery plugins ko-selectize ran into a problem where jQuery is removed from global scope.. and I think this plugin requires it.. Have you ever ran webpack +3 with knockout and jquery?

**Comment by tomasAlabes** [comment]
The loader modifies the `knockout.debug` file so you need to minify it yourself later.

You can use something like the [provide-plugin](https://webpack.js.org/plugins/provide-plugin/#usage-jquery) to replace the global calls for encapsulated calls. I use it myself for the same reason.
